# Generated by ./update.sh - do not update manually!
# Last updated: 2026-07-23
{ fetchurl }:
{
  aarch64-darwin = {
    version = "4.51.180";
    src = fetchurl {
      url = "https://downloads.slack-edge.com/desktop-releases/mac/arm64/4.51.180/Slack-4.51.180-macOS.dmg";
      hash = "sha256-6QhuZWEwQiW8ZyYTJRLMZq5MayBgX9xlBLdhttiTaoA=";
    };
  };
  x86_64-darwin = {
    version = "4.49.89";
    src = fetchurl {
      url = "https://downloads.slack-edge.com/desktop-releases/mac/x64/4.49.89/Slack-4.49.89-macOS.dmg";
      hash = "sha256-eysKaQ1SXScsL0vji+32r/NgWN0eni62+LkB4svTHUE=";
    };
  };
  x86_64-linux = {
    version = "4.51.180";
    src = fetchurl {
      url = "https://downloads.slack-edge.com/desktop-releases/linux/x64/4.51.180/slack-desktop-4.51.180-amd64.deb";
      hash = "sha256-qkXhUXlHAzdwEqmtePCyFSw2iFLghSZ65ona+1wwjqE=";
    };
  };
}
